### ISSUE TITLE
SASS-Project Part01

### ISSUE THREAD

**Issue by samirkarimov** [NamigRustamov/distantLearning#6]
#### Qeydlər
- [SASS-Project - Part01 Dərs Videosu](https://vimeo.com/725543651/e13c06b1e9)
- Layihə üçün yazılan kodlar [**Bu Repo**](https://github.com/samirkarimov/SASS-Project)-da mövcuddur

#### Mövzular
- SASS - Loops
  - for loop
  - each loop
- SASS - Lists

#### Görüləcək işlər
- Github hesabınızda SASS-Project adlı repo yaradın
- Seçdiyiniz layihənin 1 hissəsini SASS vasitəsi ilə strukturlu şəkildə yazın
- Reponun linkini comment olaraq göndərin
- Dərsdə yazılan kodları analiz edin və
  - Kod təkrarı olan hissələri comment olaraq qeyd edin
  - Kod təkrarını aradan qaldırmaq üçün təklifləriniz nələr ola bilər?

**Comment by NamigRustamov** [comment]
https://github.com/NamigRustamov/SASS-Project

**Comment by samirkarimov** [comment]
@NamigRustamov analiz edib gün ərzində izahat verəcəm Namiq

**Comment by samirkarimov** [comment]
- `app.scss` faylının adını dəyişib `_app.scss` qoy ki o faylı ayrıca compile etməsin

```css
@each $size in $sizes {
    .pl-#{size} {
        padding-left: $size+px !important;
    }
}

```

```css
@each $size in $sizes {
    .pl-#{$size} {
        padding-left: $size+px !important;
    }
}

```

dəyişikliyini et.

Bir də compile edəndə terminalda səhvlərini göstərir əslində onları analiz etsən çox daha asan şəkildə həlledəcəksən işlərini.
